Deno.serve(async (req) => {
    const corsHeaders = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
        'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
        'Access-Control-Max-Age': '86400',
    };

    if (req.method === 'OPTIONS') {
        return new Response(null, { status: 200, headers: corsHeaders });
    }

    try {
        const { content, title, type } = await req.json();

        if (!content || !title) {
            throw new Error('Content and title are required');
        }

        // Generate simple PDF content in HTML format
        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
        h2 { color: #1e40af; margin-top: 30px; }
        .vocab { background: #f3f4f6; padding: 15px; margin: 10px 0; border-left: 4px solid #2563eb; }
        .arabic { color: #059669; font-size: 1.2em; font-weight: bold; }
        .example { font-style: italic; color: #6b7280; margin-top: 10px; }
        .section { margin: 20px 0; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    <div class="section">
        ${content}
    </div>
    <footer style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.9em;">
        <p>Generated by English Learning Platform</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>
    </footer>
</body>
</html>`;

        return new Response(
            JSON.stringify({
                success: true,
                htmlContent,
                type: type || 'study-guide'
            }),
            {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                status: 200
            }
        );

    } catch (error) {
        return new Response(
            JSON.stringify({
                error: error.message
            }),
            {
                headers: { ...corsHeaders, 'Content-Type': 'application/json' },
                status: 400
            }
        );
    }
});
